name: Run my pythin             #name 為命名
on:
    push:

jobs:                           #工作
    build:                      #建造
        name: do job1
        runs-on: ubuntu-latest  #執行最新版本
        steps:
        - uses: actions/checkout@v2  #用:動作/
        - name: Run send mail py      #命名讀取該檔案
          run: |                     #讀取該檔案
            python3 send_mail.py      
        - name: Run test0713-2 py
          run: |
            python3 test0713-2.py
    build2:
        name: do job2
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@V2
        - name: Run tesr py
          run: |
           python3 test0713-2.py